# Generated by Django 4.2 on 2023-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(default='FCHUSGJWZJXKCUHP', max_length=64, primary_key=True, serialize=False)),
                ('message', models.JSONField()),
                ('key_hash', models.CharField(max_length=64)),
                ('number_of_bad_requests', models.IntegerField(default=0)),
                ('is_disposed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
